myproject/booking/urls.py
from django.urls import path
from . import views

app_name = 'booking'


urlpatterns = [
    path('',views.StoreList.as_view(), name='store_list'),
    path('store/<int:pk>/staffs/',views.StaffList.as_view(), name='staff_list'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('booking.urls')),
]

myproject/booking/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Store(models.Model):
    """店舗"""
    name = models.CharField('店名', max_length=255)

    def __str__(self):
        return self.name


class Staff(models.Model):
    """店舗スタッフ"""
    name = models.CharField('表示名', max_length=50)
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, verbose_name='ログインユーザー', on_delete=models.CASCADE
    )
    store = models.ForeignKey(Store, verbose_name='店舗', on_delete=models.CASCADE)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['user', 'store'], name='unique_staff'),
        ]

    def __str__(self):
        return f'{self.store.name} - {self.name}'


class Schedule(models.Model):
    """予約スケジュール."""
    start = models.DateTimeField('開始時間')
    end = models.DateTimeField('終了時間')
    name = models.CharField('予約者名', max_length=255)
    staff = models.ForeignKey('Staff', verbose_name='スタッフ', on_delete=models.CASCADE)

    def __str__(self):
        start = timezone.localtime(self.start).strftime('%Y/%m/%d %H:%M:%S')
        end = timezone.localtime(self.end).strftime('%Y/%m/%d %H:%M:%S')
        return f'{self.name} {start} ~ {end} {self.staff}'

myproject/booking/views.py
from django.shortcuts import get_object_or_404
from django.views import generic
from .models import Store, Staff

class StoreList(generic.ListView):
    model = Store
    ordering ='name'

class StaffList(generic.ListView):
    model = Staff
    ordering = 'name'

    def get_context_data(self,**kwargs):
        context = super().ge_context_data(**kwargs)
        context['store'] = self.store
        return context
    
    def get_queryset(self):
        store = self.store = get_object_or_404(Store, pk=self.kwargs['pk'])
        queryset = super().get_queryset().filter(store=store)
        return queryset

myproject/booking/templates/booking/base.html
<!DOCTYPE html>
<html lang="ja">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>予約サイト</title>
    <style>
        body {
            width: 960px;
            margin: 0 auto;
            padding-top: 50px;
        }

        nav > a {
            margin-right: 10px;
        }
    </style>
</head>

<body>

<nav>
    <a href="{% url 'booking:store_list' %}">Home</a>
    {% if user.is_authenticated %}
        <a href="">MyPage</a>
        <a href="">Logout</a>
    {% else %}
        <a href="">Login</a>
    {% endif %}
</nav>

{% block content %}{% endblock %}

</body>
</html>

myproject/booking/templates/booking/staff_list.html
{% extends 'booking/base.html' %}

{% block content %}

    <h1>{{ store.name }}店 スタッフ一覧</h1>
    <ul>
        {% for staff in staff_list %}
            <li><a href="">{{ staff.name }}</a></li>
        {% empty %}
            <li>まだスタッフがいません。</li>
        {% endfor %}
    </ul>
{% endblock %}

myproject/booking/templates/booking/store_list.html
{% extends 'booking/base.html' %}

{% block content %}
    <h1>店舗一覧</h1>
    <ul>
        {% for store in store_list %}
            <li><a href="{% url 'booking:staff_list' store.pk %}">{{ store.name }}</a></li>
        {% empty %}
            <li>まだ店舗がありません。</li>
        {% endfor %}
    </ul>
{% endblock %}